---
- name: Renew certbot
  ansible.builtin.cron:
    name: "renew certbot"
    minute: "0"
    hour: "1"
    job: "{{ dpl_certbot_create_renew_file }}"
    state: "{{ inv_certbot_hosts and 'present' or 'absent' }}"
