---
# Directories
- name: Create scripts directory
  ansible.builtin.file:
    path: "{{ dpl_scripts_dir }}"
    state: directory

- name: Create secrets directory
  ansible.builtin.file:
    path: "{{ dpl_secrets_dir }}"
    state: directory

- name: Create AWS dir
  ansible.builtin.file:
    path: "{{ dpl_aws_dir }}"
    state: directory
  when: use_aws_ecr

- name: Create data directory
  ansible.builtin.file:
    path: "{{ dpl_data_dir }}"
    state: directory

- name: Create data nginx directory
  ansible.builtin.file:
    path: "{{ dpl_data_dir }}/nginx"
    state: directory

- name: Create docker-compose directory
  ansible.builtin.file:
    path: "{{ inv_compose_dir }}"
    state: directory

- name: Create PostgreSQL Configuration directory
  ansible.builtin.file:
    path: "{{ dpl_postgres_dir }}"
    state: directory

- name: Create backups directory
  ansible.builtin.file:
    path: "{{ inv_app_root_path }}/backups/{{ item }}"
    state: directory
  loop:
    - db
    - filestore

# Files
- name: Create Certbot Create/Renew Script.
  ansible.builtin.template:
    src: certbot_create_renew.sh.j2
    dest: "{{ dpl_certbot_create_renew_file }}"
    mode: a+x
  when: inv_certbot_hosts

- name: Create Nginx Maintenance Image file.
  ansible.builtin.copy:
    src: "{{ inv_nginx_logo_file }}"
    dest: "{{ dpl_nginx_logo_file }}"

- name: Create Nginx Maintenance HTML file.
  ansible.builtin.copy:
    src: "{{ inv_nginx_html_file }}"
    dest: "{{ dpl_nginx_html_file }}"

# Only create if there is source path specified for it.
- name: Create Nginx Config file.
  ansible.builtin.copy:
    src: "{{ inv_nginx_conf_file }}"
    dest: "{{ dpl_nginx_conf_file }}"
  when: inv_nginx_conf_file

- name: Create PostgreSQL conf file.
  ansible.builtin.copy:
    src: "{{ inv_postgres_conf_file }}"
    dest: "{{ dpl_postgres_conf_file }}"

- name: Create PostgreSQL hba file.
  ansible.builtin.copy:
    src: "{{ inv_postgres_hba_file }}"
    dest: "{{ dpl_postgres_hba_file }}"
  when: inv_postgres_hba_file is defined

- name: Create postgres password file
  ansible.builtin.copy:
    content: "{{ inv_host_secrets.postgres_password }}"
    dest: "{{ dpl_secrets_postgres_file }}"
  no_log: true

- name: Create Odoo config file
  ansible.builtin.copy:
    content: "{{ inv_host_secrets.odoo_config }}"
    dest: "{{ dpl_secrets_odoo_config_file }}"
  no_log: true

- name: Create Domain Bundle Certificate
  ansible.builtin.copy:
    content: "{{ inv_shared_secrets.domain_bundle }}"
    dest: "{{ dpl_dpl_secrets_domain_bundle_file }}"
  no_log: true

- name: Create Domain Private Key
  ansible.builtin.copy:
    content: "{{ inv_shared_secrets.domain_key }}"
    dest: "{{ dpl_secrets_domain_key }}"
  no_log: true

- name: Create AWS Config File
  ansible.builtin.copy:
    src: "{{ inv_aws_conf_file }}"
    dest: "{{ dpl_aws_conf_file }}"
  when: use_aws_ecr

- name: Create AWS Credentials File
  ansible.builtin.copy:
    content: "{{ inv_shared_secrets.aws_credentials }}"
    dest: "{{ dpl_aws_credentials_file }}"
  when: use_aws_ecr
  no_log: true

# Intended to be used with xodoo package.
- name: Copy Migration files
  ansible.builtin.copy:
    src: "{{ inv_migrations_dir }}/"
    dest: "{{ dpl_migrations_dir }}"
  when: inv_migrations_dir is defined
