---
- name: Install docker SDK, OdooRPC and other
  ansible.builtin.pip:
    name:
      - docker==5.0.3
      - docker-compose==1.29.2
      - odoorpc==0.8.0
      # Used to manage Odoo shell operations (like password change).
      - pexpect==4.8.0
    extra_args: --user

- name: Install AWS CLI
  ansible.builtin.pip:
    name:
      - awscli==1.27.8
    extra_args: --user
  when: use_aws_ecr

- name: Log into Docker Hub
  docker_login:
    username: "{{ inv_registry_user }}"
    password: "{{ inv_shared_secrets.docker_token_r }}"
  no_log: true
  when: not use_aws_ecr

- name: Get AWS ECR token
  shell: "/opt/odoo/.local/bin/aws ecr get-login-password"
  register: aws_ecr_token
  when: use_aws_ecr

- name: Log into AWS ECR registry
  docker_login:
    registry_url: "{{ inv_aws_ecr_host }}"
    username: "AWS"
    password: "{{ aws_ecr_token.stdout }}"
    reauthorize: true
  no_log: true
  when: use_aws_ecr

- name: Pull backup service
  community.docker.docker_image:
    name: loomchild/volume-backup
    source: pull
