---
- name: Set SWAP
  ansible.builtin.include_role:
    name: geerlingguy.swap
  vars:
    swap_file_size_mb: "{{ SWAP_SIZE_MB }}"
  when: SWAP_SIZE_MB is defined

- name: Install global packages
  include_tasks: install_root.yml

- name: Set up files for root user
  include_tasks: files_root.yml

- name: Create App User
  include_tasks: app_user.yml

- name: Set up files for app user
  include_tasks: files_app.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"

- name: Install app user packages
  include_tasks: install_app.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"

- name: Set up cron jobs for app user
  include_tasks: cron_app.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"
