---

- name: Create App User
  include_tasks: app_user.yml

- name: Set up files for root user
  include_tasks: files_root.yml

- name: Set up files for app user
  include_tasks: files_app.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"

- name: Install docker and its prerequisites
  include_tasks: install.yml

- name: Set up cron jobs for app user
  include_tasks: cron_app.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"
