---
# Destination paths.
dpl_scripts_dir: "{{ inv_app_root_path }}/scripts"
dpl_postgres_dir: "{{ inv_app_root_path }}/postgres_cfg"
dpl_postgres_conf_file: "{{ dpl_postgres_dir }}/postgresql.conf"
dpl_postgres_hba_file: "{{ dpl_postgres_dir }}/pg_hba.conf"
dpl_secrets_dir: "{{ inv_app_root_path }}/.secrets"
dpl_secrets_postgres_file: "{{ dpl_secrets_dir }}/POSTGRES_PASSWORD_FILE"
dpl_secrets_odoo_config_file: "{{ dpl_secrets_dir }}/odoo.override.conf"
dpl_dpl_secrets_domain_bundle_file: "{{ dpl_secrets_dir }}/domain.bundle.crt"
dpl_secrets_domain_key: "{{ dpl_secrets_dir }}/domain.key"
dpl_aws_dir: "{{ inv_app_root_path }}/.aws"
dpl_aws_conf_file: "{{ dpl_aws_dir }}/config"
dpl_aws_credentials_file: "{{ dpl_aws_dir }}/credentials"
dpl_data_dir: "{{ inv_app_root_path }}/data"
dpl_nginx_logo_file: "{{ dpl_data_dir }}/nginx/maintenance_logo.png"
dpl_nginx_html_file: "{{ dpl_data_dir }}/nginx/custom_502.html"
dpl_nginx_conf_file: "{{ dpl_data_dir }}/nginx/nginx.conf"
# Control vars.
dpl_init_role: "{{ inv_app_root_path }}/.init_role"
dpl_force_init: false
# Helper vars.
# This path becomes available when docker is installed via pip.
docker_compose_bin: /opt/odoo/.local/bin/docker-compose
# Certbot
dpl_certbot_create_renew_file: "{{ dpl_scripts_dir }}/certbot_create_renew.sh"
