---
use_aws_ecr: false
inv_nginx_conf_file: false
inv_certbot_hosts: []
# Odoo config defaults
odoo_proxy_mode: "True"
odoo_list_db: "False"
odoo_server_wide_modules: base,web
odoo_queue_job_channels: ""
odoo_running_env: ""
inv_marabunta_custom_mig_file: null
