---
- name: Set Up Odoo (update, install modules, setup config)
  include_tasks: setup.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"

- name: Start Odoo
  community.docker.docker_compose:
    project_name: "{{ inv_project_name }}"
    project_src: "{{ inv_compose_dir }}"
  register: docker_compose_output
  become: true
  become_user: "{{ inv_app_user }}"

- name: Remove dangling docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: true
  become: true
  become_user: "{{ inv_app_user }}"
