---
- name: Initialize certbot
  include_tasks: cert_setup.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"
  when: inv_certbot_hosts

- name: Set Up Odoo (update, install modules, setup config)
  include_tasks: setup.yml
  args:
    apply:
      become: true
      become_user: "{{ inv_app_user }}"

- name: Start Odoo
  community.docker.docker_compose:
    project_name: "{{ inv_project_name }}"
    project_src: "{{ inv_compose_dir }}"
  register: docker_compose_output
  become: true
  become_user: "{{ inv_app_user }}"

- name: Remove dangling docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: true
  become: true
  become_user: "{{ inv_app_user }}"

- name: Reload Nginx
  ansible.builtin.command: docker exec -it app_web_1 nginx -s reload
  become: true
  become_user: "{{ inv_app_user }}"

- name: Force rebuild all containers
  ansible.builtin.command:
    argv:
      - "{{ docker_compose_bin }}"
      - down
      - "&&"
      - "{{ docker_compose_bin }}"
      - up
      - -d
  args:
    chdir: "{{ inv_compose_dir }}"
  become: true
  become_user: "{{ inv_app_user }}"
  when: force_rebuild_containers
