---
- name: Pull images
  ansible.builtin.command:
    argv:
      - "{{ docker_compose_bin }}"
      - pull
    chdir: "{{ inv_compose_dir }}"

- name: Initilize odoo DB
  ansible.builtin.command:
    argv:
      - "{{ docker_compose_bin }}"
      - run
      - --rm
      - odoo
      - fc-odoo
      - --stop-after-init
    chdir: "{{ inv_compose_dir }}"

- name: Force Update Specified Odoo Modules
  ansible.builtin.command:
    argv:
      - "{{ docker_compose_bin }}"
      - run
      - --rm
      - odoo
      - fc-odoo
      - -u
      - "{{ odoo_update_modules_list }}"
      - --stop-after-init
    chdir: "{{ inv_compose_dir }}"
  when: odoo_update_modules_list is defined

- name: Update Odoo modules
  ansible.builtin.command:
    argv:
      - "{{ docker_compose_bin }}"
      - run
      - --rm
      - odoo
      - fc-update
      - --ignore-core-addons
      - -d
      - "{{ inv_db_name }}"
    chdir: "{{ inv_compose_dir }}"
  register: docker_compose_output

- name: Run Maraplus to setup Odoo.
  ansible.builtin.command: "{{ docker_compose_bin }} run --rm odoo fc-maraplus"
  args:
    chdir: "{{ inv_compose_dir }}"

# We run these migrations to set up/change custom data for specific customer.
# Thats why it is run at the end.

- name: Run common migration
  ansible.builtin.include_role:
    name: migration
  vars:
    migration_path: /opt/odoo/common_migrations
  when: inv_common_migrations_dir is defined and inv_common_migrations_dir
- name: Run migration
  ansible.builtin.include_role:
    name: migration
  vars:
    migration_path: /opt/odoo/migrations
  when: inv_migrations_dir is defined
