---
- name: Start Odoo
  community.docker.docker_compose:
    project_name: "{{ inv_project_name }}"
    project_src: "{{ inv_compose_dir }}"
  register: docker_compose_output
  become: true
  become_user: "{{ inv_app_user }}"

- name: Save Odoo container status
  set_fact:
    odoo_ip: "{{ docker_compose_output.services.odoo.app_odoo_1.networks\
      .app_backend.IPAddress }}"

- name: Wait for Odoo port to be open
  wait_for:
    host: "{{ odoo_ip }}"
    port: 8069
    state: started

- name: Change Odoo admin user password
  include_role:
    name: _change_user_pwd
  vars:
    user_login: "{{ inv_host_secrets.odoo_admin_user_login }}"
    user_pwd: "{{ inv_host_secrets.odoo_admin_user_pwd }}"

- name: Create Postgres Users
  include_role:
    name: pg_user
  vars:
    pg_user_name: "{{ item.name }}"
    pg_user_password: "{{ item.password }}"
    pg_user_priv_mode: "{{ item.priv_mode }}"
  loop: "{{ inv_pg_users }}"

# Deprecated.
- name: Create .init_role to mark initiation as done.
  ansible.builtin.template:
    src: .init_role
    dest: "{{ dpl_init_role }}"
