---

- name: Save Odoo container status
  set_fact:
    odoo_ip: "{{ docker_compose_output.services.odoo.app_odoo_1.networks\
      .app_backend.IPAddress }}"

- name: Wait for Odoo port to be open
  wait_for:
    host: "{{ odoo_ip }}"
    port: 8069
    state: started

- name: Change Odoo admin user password
  include_role:
    name: _change_user_pwd
  vars:
    user_login: "{{ inv_host_secrets.odoo_admin_user_login }}"
    user_pwd: "{{ inv_host_secrets.odoo_admin_user_pwd }}"

- name: Create .init_role to mark initiation as done.
  ansible.builtin.template:
    src: .init_role
    dest: "{{ dpl_init_role }}"
