---
- name: Setup access from delegated to this host
  include_tasks: delegated_access.yml

- name: Run backup on delegated host
  include_tasks: backup.yml
  when: delegated_do_src_backup

- name: Run restore on this host (with filestore sync)
  include_tasks: restore.yml

- name: Set up Odoo
  include_tasks: setup_odoo.yml

- name: Start Odoo
  community.docker.docker_compose:
    project_name: "{{ inv_project_name }}"
    project_src: "{{ inv_compose_dir }}"
  register: docker_compose_output
  become: true
  become_user: "{{ inv_app_user }}"

# To wait for odoo to be running and change admin password
- name: Post handle delegated restore.
  ansible.builtin.include_role:
    name: post_init

# Expects odoo container to be up!
- name: Reset DB params
  ansible.builtin.expect:
    command: docker exec -it app_odoo_1 bash -c 'odoo shell -p 8055'
    # TODO: for now we re-force web.base.url to use default port,
    # because when we connect with `8055` odoo will use that port
    # instead which is not correct. We should redesign docker, so we
    # could access odoo shell with normal docker compose run, so we
    # would be accessing it with all proper parameters on.
    responses:
      '>>> ':
        - ICP = env['ir.config_parameter']
        - ICP.init(force=True)
        - ICP.set_param('web.base.url', 'http://localhost:8069')
        - env.cr.commit()
        - exit()
  become: true
  become_user: "{{ inv_app_user }}"
  no_log: true
