---
- hosts: "{{ target | default('test_prod') }}"
  pre_tasks:
    - name: Prepare for prod deployment
      include_role:
        name: _prepare_deploy
  roles:
    - {
      role: pre_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
    - {role: _prepare_compose, tags: prep_compose}
    - {role: backup, tags: backup}
    - {role: container, tags: container}
    - {
      role: post_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
