---
- hosts: "{{ target | default('test_stage') }}"
  strategy: "{{ strategy | default('free') }}"
  pre_tasks:
    - name: Prepare for dev deployment
      include_role:
        name: _prepare_deploy
  roles:
    - {
      role: pre_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
    - {role: _prepare_compose, tags: prepare_compose}
    - {role: _dropdb, tags: dropdb}
    - {role: container, tags: container}
    - {
      role: post_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
