---
- hosts: "{{ target | default('test_stage') }}"
  strategy: "{{ strategy | default('free') }}"
  pre_tasks:
    - name: Prepare for stage deployment
      include_role:
        name: _prepare_deploy
  roles:
    - {role: pre_init}
    - {role: container, tags: container}
    - {
      role: post_init,
      tags: init,
    }
