---
- hosts: "{{ target | default('test_stage') }}"
  strategy: "{{ strategy | default('free') }}"
  pre_tasks:
    - name: Prepare for stage deployment
      include_role:
        name: _prepare_deploy
  roles:
    - pre_init
    - container
    - post_init
