---
- hosts: "{{ target | default('test_prod') }}"
  strategy: "{{ strategy | default('free') }}"
  pre_tasks:
    - name: Prepare for prod deployment
      include_role:
        name: _prepare_deploy
  roles:
    - {
      role: pre_init,
      tags: init,
    }
    - {role: container, tags: container}
    - {
      role: post_init,
      tags: init,
    }
