---
# TODO: add cron job for daily backups.
# TODO: add Odoo setup mode, to install needed modules, set needed
# params etc.
# TODO: add upgrade mode, to automatically upgrade needed modules (
# might be able to use click-odoo-update script).
# TODO: might be useful to make it possible to change user password
# without a need to log into Odoo. This way we would not need to know
# old password.
- hosts: "{{ target | default('test_prod') }}"
  pre_tasks:
    - name: Prepare for prod deployment
      include_role:
        name: _prepare_deploy
  roles:
    - {
      role: pre_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
    - {role: backup, tags: backup}
    - {role: container, tags: container}
    - {
      role: post_init,
      tags: init,
      when: init_role_data.stat.path is not defined or dpl_force_init
    }
