---
# Helper role to find backups.

- name: Find backup files
  block:
    - name: Find existing db backups.
      ansible.builtin.find:
        paths: "{{ inv_app_root_path }}/backups/db"
      register: backup_db_files

    - name: Find existing filestore backups.
      ansible.builtin.find:
        paths: "{{ inv_app_root_path }}/backups/filestore"
      register: backup_filestore_files
  delegate_to: "{{ inv_backups_host | default(inventory_hostname) }}"

- name: Sort backups by creation time.
  ansible.builtin.set_fact:
    sorted_backup_db_files: "{{ backup_db_files.files|
                  sort(attribute='mtime')|
                  map(attribute='path')|
                  list }}"
    sorted_backup_filestore_files: "{{ backup_filestore_files.files|
                  sort(attribute='mtime')|
                  map(attribute='path')|
                  list }}"
